version: '3'

services:
  pause:
    image: "gcr.io/google_containers/pause-amd64:3.0"
    networks:
      - pausenet
    ports:
      - "2181:2181"
      - "9092:9092"
      - "9093:9093"
      - "9094:9094"
      - "9095:9095"
    container_name: pause
  zookeeper:
    depends_on:
      - pause
    image: "zmstone/kafka:${KAFKA_VERSION:-1.1}"
    container_name: zookeeper
    command: run zookeeper
    ipc: container:pause
    network_mode: service:pause
  kafka:
    depends_on:
      - pause
      - zookeeper
    image: "zmstone/kafka:${KAFKA_VERSION:-1.1}"
    container_name: 'kafka'
    ipc: container:pause
    network_mode: service:pause
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "localhost:2181"
      KAFKA_CREATE_TOPICS: "${TOPICS}"

networks:
  pausenet:
